### ISSUE TITLE
换个像 org 名一样内涵的名字吧

### ISSUE THREAD

**Issue by ushuz** [xghgzxfp/sexycroupier#3]
@xghgzxfp/xghgzxfp

我提一个：dqd 懂球帝

**Comment by Grant6899** [comment]
dqd是啥

**Comment by ushuz** [comment]
@Grant6899 懂球帝啊

**Comment by Grant6899** [comment]
Why is this issue still alive? @Anserw @ushuz

**Comment by ushuz** [comment]
Cuz nobody Anserwed

**Comment by Grant6899** [comment]
I thought the current one is good enough, isn't it?

**Comment by Grant6899** [comment]
I mean xghgzxfp

**Comment by ushuz** [comment]
Eh the issue is about repo name `bet_web`, not org name. xghgzxfp is the best.

**Comment by Grant6899** [comment]
Let's vote!

My proposal: SexyCroupier

Please give me a thumb up if you agree!

**Comment by Anserw** [comment]
👍

Grant6899 <notifications@github.com>于2018年6月9日周六 下午12:41写道：

**Comment by ushuz** [comment]
**SexyCroupier** may be too straightforward, how about: **croupier.avi**?

**Comment by Grant6899** [comment]
Whatever you like
